import {
  PERMISSION_CODES,
  PROGRAMME_CODES,
  SOURCE_CODES,
  STATUS_CODES,
  type ProgrammeCode,
  type SourceCode,
  type StatusCode,
} from "@/config/codes";
import type { Principal } from "@/lib/auth";
import { ERROR_CODES } from "@/lib/result";
import { Enquiry, StaffProfile, User } from "@/models";
import { createEnquiry } from "@/services/enquiry.service";
import { changeStatus, scheduleFollowUp } from "@/services/workflow.service";

/**
 * Synthetic demo enquiries.
 *
 *     npm run seed -- --enquiries=40
 *
 * ─── EVERY RECORD GOES THROUGH `createEnquiry()` ───────────────────────────────
 *
 * Not one document is inserted directly. That is the rule this file exists to
 * respect (conventions §15 and §17): `createEnquiry()` is the single enquiry write
 * path, and it owns duplicate detection, round-robin assignment and the `created`
 * history event. A seed that inserted documents would be a second implementation of
 * all three, and the two would drift — at which point the demo data would no longer
 * demonstrate the system's actual behaviour, which is the only reason it exists.
 *
 * A useful side effect: the demo data is generated BY the code under test, so a bug
 * in assignment or duplicate flagging shows up as visibly wrong seed output rather
 * than hiding behind hand-built fixtures.
 *
 * ─── ALL DATA IS SYNTHETIC ─────────────────────────────────────────────────────
 *
 * No real SCCT student or parent appears here, and none can: the surnames are
 * openly fake (Demo, Sample, Placeholder…), and every email is on `example.invalid`
 * — a reserved TLD that can never resolve, so nothing here can reach a real inbox
 * even by accident.
 *
 * Phone numbers are generated from a fixed arithmetic series in the valid Indian
 * mobile range. They are deliberately NOT random: a rerun must produce the same
 * numbers, or "re-run the seed" would mean "get a different database".
 *
 * ─── RERUNNING IS SAFE, AND PROVES THE IDEMPOTENCY KEY WORKS ───────────────────
 *
 * Each generated enquiry carries a deterministic `idempotencyKey`
 * (`seed-demo-0001`). So a second run resolves every one of them to the record that
 * already exists and creates nothing — the same mechanism that protects a
 * double-clicked submission on the public form, exercised by the seed itself.
 *
 * ─── STAGE AND FOLLOW-UP VARIETY GOES THROUGH THE WORKFLOW SERVICES ────────────
 *
 * A database where every enquiry sits in the default stage with no follow-up cannot
 * demonstrate the queue's stage filter, its urgency sort or its overdue badge — and
 * a filter nobody has ever seen return rows is a filter nobody knows is broken.
 *
 * So the shaping pass calls `changeStatus()` and `scheduleFollowUp()` — the same
 * functions the staff interface calls, with a real principal and its real permission
 * checks. It does NOT write `status`, `nextFollowUpAt`, `FollowUp` or `EnquiryEvent`
 * directly. The result is demo data whose history genuinely happened: every stage
 * change in the log was performed, by an account, in order.
 *
 * The one liberty taken is BACKDATING: a demo database needs enquiries that arrived
 * weeks ago, and `createdAt` is set by Mongoose timestamps. That single field is
 * adjusted directly, and it is called out in the function that does it rather than
 * buried.
 */

const SURNAMES = [
  "Demo",
  "Sample",
  "Example",
  "Placeholder",
  "Testcase",
  "Fixture",
  "Specimen",
  "Synthetic",
];

const FIRST_NAMES = [
  "Aarav", "Ananya", "Ishaan", "Diya", "Kabir", "Meera", "Rohan", "Saanvi",
  "Vivaan", "Aditi", "Arjun", "Kavya", "Neel", "Priya", "Rehan", "Tara",
  "Yash", "Zoya", "Farhan", "Nisha",
];

const CITIES = ["Mumbai", "Thane", "Navi Mumbai", "Kalyan", "Vasai", "Panvel"];

const PROGRAMMES: ProgrammeCode[] = Object.values(PROGRAMME_CODES);

/**
 * Sources drawn from BOTH of SCCT's unreconciled taxonomies, on purpose.
 *
 * The two conflicting source lists are a real finding, not an inconvenience to tidy
 * away. Demo data spanning both is what makes the problem visible in the reporting
 * view — where a manager sees counts split across two overlapping vocabularies and
 * asks the question SCCT needs to answer (open question 2).
 */
const SOURCES: SourceCode[] = [
  SOURCE_CODES.WALK_IN,
  SOURCE_CODES.SOCIAL_MEDIA,
  SOURCE_CODES.WEBSITE,
  SOURCE_CODES.REFERENCE,
  SOURCE_CODES.IN_HOUSE_STUDENT,
  SOURCE_CODES.TEACHER_CALLING_PURCHASED_DATA,
  SOURCE_CODES.UNIVERSITY_TAG_LIST,
  SOURCE_CODES.GOOGLE_SEARCH,
  SOURCE_CODES.FRIENDS_FAMILY,
  SOURCE_CODES.SCHOOL_TEACHER,
  SOURCE_CODES.TRAIN_ADVERTISEMENT,
  SOURCE_CODES.UNATTRIBUTED,
];

const HSC_STREAMS = ["Commerce", "Science", "Arts"];
const HSC_BANDS = ["Below 50%", "50–60%", "60–70%", "70–80%", "Above 80%"];

/**
 * A tiny deterministic generator, so the demo database is reproducible.
 *
 * `Math.random()` would make every seed run produce different data, which breaks
 * the one property demo data needs: that a bug someone reports on Tuesday can be
 * looked at on Wednesday.
 */
function sequence(seed: number) {
  let value = seed;
  return () => {
    // A standard 32-bit linear congruential step. Not good randomness — it does not
    // need to be, it needs to be the same every time.
    value = (value * 1103515245 + 12345) & 0x7fffffff;
    return value;
  };
}

function phoneFor(index: number): string {
  // 10 digits starting 6–9, per isValidIndianMobile. A fixed stride keeps the
  // numbers distinct and the series obviously artificial.
  const base = 9_000_000_000 + index * 137_909;
  return String(base);
}

export type SeedEnquiryOptions = {
  count: number;
  /** Print each record as it is created. Off during tests. */
  verbose?: boolean;
  /**
   * Move some enquiries through stages and schedule follow-ups, via the workflow
   * services. Off by default so a plain enquiry seed stays a plain enquiry seed.
   */
  shape?: boolean;
  /** Fixed "now", so a seeded database is reproducible. Defaults to the real clock. */
  now?: Date;
};

/**
 * The stage mix, chosen so every queue filter returns something.
 *
 * Deliberately weighted towards the early stages: a real admissions funnel has far
 * more new enquiries than enrolments, and demo data that splits evenly across five
 * stages would make the reporting view look like a system nobody uses.
 */
const STAGE_MIX: Array<{ code: StatusCode; weight: number }> = [
  { code: STATUS_CODES.NEW, weight: 8 },
  { code: STATUS_CODES.CONTACTED, weight: 6 },
  { code: STATUS_CODES.IN_DISCUSSION, weight: 4 },
  { code: STATUS_CODES.CLOSED_ENROLLED, weight: 2 },
  { code: STATUS_CODES.CLOSED_NOT_PROCEEDING, weight: 2 },
];

export async function seedEnquiries({
  count,
  verbose = false,
  shape = false,
  now = new Date(),
}: SeedEnquiryOptions) {
  const next = sequence(20260821);

  let created = 0;
  let replayed = 0;
  let duplicatesFlagged = 0;
  let unassigned = 0;
  const failures: string[] = [];

  // What was actually generated, so a deliberate repeat can reuse a real earlier
  // record's phone and programme rather than recomputing a guess at them.
  const generated: Array<{ phone: string; programmeCode: ProgrammeCode }> = [];

  for (let index = 0; index < count; index += 1) {
    const firstName = FIRST_NAMES[index % FIRST_NAMES.length];
    const surname = SURNAMES[next() % SURNAMES.length];
    const fullName = `${firstName} ${surname}`;

    const programmeIndex = next() % PROGRAMMES.length;

    /**
     * Two deliberate collisions per twelve records, and they are the point of this
     * generator rather than an accident of it:
     *
     *   index % 12 === 7  — reuses an earlier record's phone with the SAME
     *                       programme, so the duplicate rule flags it. Without one
     *                       of these, the duplicate badge in the queue is never
     *                       exercised by demo data and nobody notices it is broken.
     *
     *   index % 12 === 11 — reuses an earlier phone with a DIFFERENT programme,
     *                       which must NOT be flagged. One person may genuinely
     *                       enquire about B.Com and B.Sc IT, and this record is what
     *                       proves the rule distinguishes the two cases instead of
     *                       flagging every repeat contact.
     */
    // `index - 7` is the record being echoed, so index 7 is the earliest that can
    // echo anything. Both patterns therefore fire from the first dozen records
    // onwards — which matters, because a seed of 10 that produced no duplicate pair
    // would leave the duplicate badge untested by demo data.
    const isSameProgrammeRepeat = index % 12 === 7;
    const isOtherProgrammeRepeat = index % 12 === 11;

    // The record being echoed. Read from what was really generated, so the two
    // cases below are genuinely "same programme" and "different programme" rather
    // than two guesses that might coincide.
    const echoed = generated[index - 7];

    const phone = echoed && (isSameProgrammeRepeat || isOtherProgrammeRepeat)
      ? echoed.phone
      : phoneFor(index);

    const programmeCode = !echoed
      ? PROGRAMMES[programmeIndex]
      : isSameProgrammeRepeat
        ? echoed.programmeCode
        : isOtherProgrammeRepeat
          ? // Guaranteed different: step one place on from the echoed programme.
            PROGRAMMES[
              (PROGRAMMES.indexOf(echoed.programmeCode) + 1) % PROGRAMMES.length
            ]
          : PROGRAMMES[programmeIndex];

    generated.push({ phone, programmeCode });

    const sourceCode = SOURCES[next() % SOURCES.length];

    // A website submission is by definition self-submitted; a purchased list or a
    // university tag list is not, and recording that honestly is what makes the
    // retention question (open question 9) answerable later.
    const isSelfService =
      sourceCode === SOURCE_CODES.WEBSITE || sourceCode === SOURCE_CODES.SOCIAL_MEDIA;

    const isSourcedList =
      sourceCode === SOURCE_CODES.TEACHER_CALLING_PURCHASED_DATA ||
      sourceCode === SOURCE_CODES.UNIVERSITY_TAG_LIST;

    // Roughly one in four has no email, matching the reason the field is optional:
    // walk-ins and phone enquiries frequently do not have one, and that shape needs
    // to exist in the demo data or the queue looks tidier than reality.
    const hasEmail = next() % 4 !== 0;

    const result = await createEnquiry({
      fullName,
      phone,
      email: hasEmail
        ? `${firstName}.${surname}.${index}`.toLowerCase() + "@example.invalid"
        : undefined,

      programmeCode,
      sourceCode,

      message:
        next() % 3 === 0
          ? "Synthetic demo enquiry. Asking about fees, timings and eligibility."
          : undefined,

      city: CITIES[next() % CITIES.length],
      hscStream: HSC_STREAMS[next() % HSC_STREAMS.length],
      hscPercentageBand: HSC_BANDS[next() % HSC_BANDS.length],
      previousInstitution: `${SURNAMES[next() % SURNAMES.length]} Junior College (synthetic)`,

      // `public_form` for the self-service routes, `staff_capture` for the rest —
      // because a walk-in typed in by a teacher genuinely is a staff capture, and
      // conflating the two would corrupt the capture-channel figure.
      captureChannel: isSelfService ? "public_form" : "staff_capture",
      consentBasis: isSelfService
        ? "self_submitted"
        : isSourcedList
          ? "sourced_list"
          : "verbal_to_staff",

      // Deterministic, so a rerun resolves instead of duplicating. See the note above.
      idempotencyKey: `seed-demo-${String(index).padStart(4, "0")}`,
    });

    if (!result.ok) {
      failures.push(`${fullName}: ${result.message}`);
      continue;
    }

    if (result.data.replayed) replayed += 1;
    else created += 1;

    if (result.data.possibleDuplicates.length > 0) duplicatesFlagged += 1;
    if (result.data.assignmentReason === "no_eligible_staff") unassigned += 1;

    if (verbose) {
      console.log(
        `    ${result.data.enquiry.enquiryNumber}  ${fullName.padEnd(24)}` +
          `${programmeCode.padEnd(9)}${result.data.replayed ? "already present" : "created"}` +
          (result.data.possibleDuplicates.length > 0 ? "  ← possible duplicate" : ""),
      );
    }
  }

  const shaping = shape ? await shapeWorkflow({ next, now, verbose, failures }) : null;

  // Failures are RETURNED, not swallowed. A seed that half-completed and reported
  // success is worse than one that stops.
  return {
    label: "enquiries",
    total: count,
    created,
    replayed,
    duplicatesFlagged,
    unassigned,
    stagesMoved: shaping?.stagesMoved ?? 0,
    followUpsScheduled: shaping?.followUpsScheduled ?? 0,
    backdated: shaping?.backdated ?? 0,
    failures,
  };
}

/**
 * Move enquiries through stages and schedule follow-ups — through the real services.
 *
 * THE PRINCIPAL IS REAL, and its permissions are the seeded admin's. So every call
 * below passes the same authorization and concurrency checks a staff member's click
 * would: if `changeStatus` refused a stage move, this seed would report a failure
 * rather than quietly producing a database the app could not have created.
 */
async function shapeWorkflow({
  next,
  now,
  verbose,
  failures,
}: {
  next: () => number;
  now: Date;
  verbose: boolean;
  failures: string[];
}) {
  const admin = await User.findOne({ email: "admin1@demo.scct-enquiry.local" })
    .select("_id")
    .lean();

  if (!admin) {
    failures.push("shaping skipped: the admin demo account is not seeded");
    return { stagesMoved: 0, followUpsScheduled: 0, backdated: 0 };
  }

  const profile = await StaffProfile.findOne({ user: admin._id }).select("_id").lean();

  const principal: Principal = {
    userId: String(admin._id),
    email: "admin1@demo.scct-enquiry.local",
    displayName: "Seed (admin1)",
    staffProfileId: profile ? String(profile._id) : null,
    roleCodes: ["admin"],
    // The two the shaping actually needs. Listed explicitly rather than granting
    // everything, so a service that started requiring a new permission would fail
    // here loudly instead of silently passing because the seed is omnipotent.
    permissions: [
      PERMISSION_CODES.ENQUIRY_UPDATE_ALL,
      PERMISSION_CODES.ENQUIRY_UPDATE_OWN,
      PERMISSION_CODES.ENQUIRY_VIEW_ALL,
    ],
  };

  // Only records this seed created, and only ones still in the default stage — so a
  // rerun does not march every enquiry one stage further each time, and a real
  // enquiry captured through the form is never touched.
  const enquiries = await Enquiry.find({ idempotencyKey: { $regex: /^seed-demo-/ } })
    .select("_id enquiryNumber status createdAt")
    .sort({ enquiryNumber: 1 })
    .lean();

  const weighted = STAGE_MIX.flatMap((stage) => Array<StatusCode>(stage.weight).fill(stage.code));

  let stagesMoved = 0;
  let followUpsScheduled = 0;
  let backdated = 0;

  for (const [index, enquiry] of enquiries.entries()) {
    /**
     * BACKDATING — the one direct write in this file.
     *
     * `createdAt` is set by Mongoose timestamps, so every seeded enquiry would
     * otherwise have arrived in the same second. A queue where nothing is older than
     * a minute cannot show the date column, the oldest-first sort or anything that
     * looks like a real week's work. There is no service that owns "pretend this
     * arrived last Tuesday", because in production nothing ever should.
     */
    const daysAgo = index % 45;

    if (daysAgo > 0) {
      const createdAt = new Date(now);
      createdAt.setDate(createdAt.getDate() - daysAgo);

      await Enquiry.updateOne(
        { _id: enquiry._id },
        { $set: { createdAt } },
        // Timestamps off for this one write, or Mongoose would overwrite the value
        // being set with the current time — which is a genuinely confusing bug to
        // watch happen.
        { timestamps: false },
      );
      backdated += 1;
    }

    // ── stage, via changeStatus() ────────────────────────────────────────────
    const target = weighted[next() % weighted.length];

    if (target !== STATUS_CODES.NEW) {
      const moved = await changeStatus(principal, String(enquiry._id), {
        fromStatusCode: STATUS_CODES.NEW,
        toStatusCode: target,
        note: "Synthetic demo data — stage set by the seed.",
      });

      if (moved.ok) stagesMoved += 1;
      // A conflict here is expected on a rerun: the enquiry has already been moved
      // out of NEW, so the guard correctly refuses. Not a failure — and it is a
      // small proof that the concurrency guard works, on every seed rerun.
      else if (moved.code !== ERROR_CODES.CONFLICT) {
        failures.push(`${enquiry.enquiryNumber} stage: ${moved.message}`);
      }
    }

    /**
     * ── follow-up, via scheduleFollowUp() ────────────────────────────────────
     *
     * Roughly two in three get one, spread from overdue to a fortnight out, so the
     * overdue badge, the "due today" filter and the urgency sort all have rows to
     * return. A terminal stage gets none — a closed enquiry with a scheduled call is
     * the kind of nonsense that makes a demo database untrustworthy.
     */
    const isTerminal =
      target === STATUS_CODES.CLOSED_ENROLLED ||
      target === STATUS_CODES.CLOSED_NOT_PROCEEDING;

    if (!isTerminal && next() % 3 !== 0) {
      // -7 … +13 days. Past dates are intentional and are how the overdue badge gets
      // exercised. Note that `followUpSchema` — the API's input validation — refuses
      // a date more than a day old, because a human typing one has almost certainly
      // mistyped the year. The seed calls the SERVICE, not the endpoint, so it is
      // not subject to that rule: backfilling history is a different act from
      // someone scheduling a call, and only the second needs protecting from typos.
      const offsetDays = (next() % 21) - 7;

      const dueAt = new Date(now);
      dueAt.setDate(dueAt.getDate() + offsetDays);

      const scheduled = await scheduleFollowUp(principal, String(enquiry._id), {
        dueAt: dueAt.toISOString(),
        note: "Synthetic demo data — follow-up set by the seed.",
      });

      if (scheduled.ok) followUpsScheduled += 1;
      else failures.push(`${enquiry.enquiryNumber} follow-up: ${scheduled.message}`);
    }

    if (verbose && index % 10 === 0) {
      console.log(`    shaped ${index + 1}/${enquiries.length}`);
    }
  }

  return { stagesMoved, followUpsScheduled, backdated };
}
