import "../load-env";

import mongoose from "mongoose";

import { db, disconnectDb } from "@/lib/db";

import { seedPermissions } from "./permissions";
import { seedProgrammes } from "./programmes";
import { seedRoles } from "./roles";
import { seedSources } from "./sources";
import { seedStaff } from "./staff";
import { seedStatuses } from "./statuses";

/**
 * Seed the system's configuration and its synthetic staff accounts.
 *
 *     npm run seed
 *
 * IDEMPOTENT AND NON-DESTRUCTIVE. Every write is an upsert matched on `code`.
 * Running this twice leaves a working system exactly as it found it, which is the
 * property that makes it safe to point at the deployed database. Nothing here
 * deletes or drops anything — that is `npm run db:reset`, which is a separate,
 * guarded, explicitly destructive script.
 *
 * ORDER IS A DEPENDENCY CHAIN, not a preference:
 *   permissions → roles (reference permission ids) → staff (reference role ids)
 * The three lookup tables have no dependencies and could run in parallel; they
 * run in sequence anyway, because an M0 cluster gains nothing from five
 * concurrent writes and sequential output is readable when something fails.
 *
 * WHAT IS NOT HERE YET: the synthetic demo ENQUIRIES. They are generated by
 * calling `createEnquiry()` in `services/enquiry.service.ts` — the single write
 * path (conventions §15) — rather than by inserting documents directly. Writing
 * a second, parallel enquiry-creation path in a seed script would duplicate the
 * duplicate-detection, round-robin and history rules, and the two would drift.
 * So enquiry generation lands with that service, and this file gains an
 * `--enquiries=<n>` flag at that point.
 */

async function main() {
  await db();

  console.log(`\n  Seeding "${mongoose.connection.name}"\n`);

  const permissions = await seedPermissions();
  const roles = await seedRoles(permissions.ids);
  const staff = await seedStaff(roles.ids);
  const programmes = await seedProgrammes();
  const sources = await seedSources();
  const statuses = await seedStatuses();

  const steps = [permissions, roles, staff, programmes, sources, statuses];

  for (const step of steps) {
    const unchanged = step.total - step.created;
    console.log(
      `  ${step.label.padEnd(14)} ${String(step.total).padStart(3)} total` +
        `   ${step.created} created` +
        `   ${unchanged} already present`,
    );
  }

  console.log("\n  Demo logins — SYNTHETIC ACCOUNTS, password from DEMO_PASSWORD:\n");
  for (const account of staff.accounts) {
    console.log(
      `    ${account.email.padEnd(40)} ${account.role.padEnd(11)}` +
        `${account.eligible ? "eligible for assignment" : "not in assignment rota"}`,
    );
  }

  console.log(
    "\n  Statuses and the source taxonomy are UNCONFIRMED PLACEHOLDERS.\n" +
      "  Indexes are NOT created by this script — run `npm run db:indexes`.\n",
  );
}

main()
  .catch((err) => {
    // Explicit failure, non-zero exit. A seed that half-completed and reported
    // success is worse than one that stops: the next thing to run would be the
    // app, against configuration that is missing a row nothing warned about.
    console.error("\n  Seed failed:", err instanceof Error ? err.message : err, "\n");
    process.exitCode = 1;
  })
  .finally(async () => {
    await disconnectDb();
  });
